version: 0.2

phases:
  install:
    runtime-versions:
      golang: 1.12

  pre_build:
    commands:
      - go version
      - ls -la
      # Run all tests included with our application
      - go test ./...

  build:
    commands:

      # Build our application
      - go build -o bin/goscratch

artifacts:
  files:
    - bin/*
    - buildspec.yml
