version: 0.2

phases:
  install:
    runtime-versions:
      golang: 1.12

  pre_build:
    commands:
      # Run all tests included with our application
      - make test

  build:
    commands:
      # Build our application
      - make build

artifacts:
  files:
    - bin/**/*
