version: 0.2

phases:
  install:
    runtime-versions:
      golang: 1.12
    commands:
      - npm install

  build:
    commands:
      - mv $CODEBUILD_SRC_DIR_BuildArtifact/bin/ .
      - make deploy
