service: user-service
frameworkVersion: '>=1.28.0 <2.0.0'

provider:
  name: aws
  runtime: go1.x

custom:
  functionsBasePath: bin/awslambda/

package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  get-one:
    handler: getone
    events:
      - http:
          path: /{userId}
          method: get

plugins:
  - serverless-functions-base-path
